### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by hugo9655** [NotJoeMartinez/yt-fts#180]
I've ran the pip install command multiple times after running into a few errors and needing to install more things.

Eventually I ran it and it said "requirement already satisfied" a bunch of times, so I assumed it was installed.

Then I try using it:
`yt-fts: The term 'yt-fts' is not recognized as a name of a cmdlet, function, script file, or executable program.`

Is there another way I can install/use this?

**Comment by NotJoeMartinez** [comment]
Are you on a unix machine? If so did you install with pip globally or within a virtual env? Try running `which yt-fts`

**Comment by NotJoeMartinez** [comment]
I'll look into testing on a windows machine, thanks

**Comment by TeddyBear06** [comment]
Hi there,

This is due to a missing path in your PATH (Windows environment variable).

I assume you've installed `Python 3.13` using `Windows Store` (if not, adapt the Python installation path).

Please add this PATH (changing {YOUR_USERNAME} with your Windows username) : 

`C:\Users\{YOUR_USERNAME}\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\Scripts`

It needs to point to the Scripts folder (this is where your .exe files resides).

![explorer_bRXh5RTyGc](https://github.com/user-attachments/assets/bd7eb0aa-5afc-4b1a-bd4e-73119e46cd83)

Once it's done, it works perfectly ;-)

![WindowsTerminal_oV5Q6yQmTc](https://github.com/user-attachments/assets/c458dad4-71d1-40bf-b10c-bb46417d129a)

To modify the Windows PATH environment variable (you can find the right way to do it regarding your Windows version around on the net, this is just the idea of how to do it):

1. Right-click My Computer (either on the Desktop or the Start menu). Click Properties.
2. In the System Properties dialog box, click the Advanced tab.
3. Click Environment Variables.
4. In the top list, scroll down to the PATH variable under user variables, select it, and click Edit. Note: If the PATH variable does not exist, click New and enter PATH for the Variable Name.
