### ISSUE TITLE
Alias for channel

### ISSUE THREAD

**Issue by fuyu0425** [NotJoeMartinez/yt-fts#3]
Hi, first thanks for this useful package!

It would be great if it can support alias.

like
```
python3 yt_fts.py alias [NAME] [channel_id]
python3 yt_fts.py search [ALIAS_NAME or ID] [search text]
``` 
It would be better: when downloading, we can also specify the alias and it would create it automatically.

**Comment by TeddyBear06** [comment]
@fuyu0425 At first, I tought too that aliasing could be a nice feature.

But the "complexity" (database structure modifications, alias uniqueness checking...) involved seems not justified as the _list_ command exists and address this specific issue:

> Will list all of your downloaded channels 
```bash
python yt_fts.py list
```

output:
```
Listing channels
channel_id                channel_name         channel_url
------------------------  -------------------  ---------------------------------------------------------------
UC4woSp8ITBoYDmjkukhEhxg  The Tim Dillon Show  https://www.youtube.com/channel/UC4woSp8ITBoYDmjkukhEhxg/videos
```

I think that it's not because you did choose an alias that it will be easier to remember than read the output of the _list_ command (just my opinion).

**Comment by NotJoeMartinez** [comment]
We could use the `ROWID` column as an alias, it wouldn't involve modifying the db and would be limited to small integers to the left of the `channel_id` column when printing.

**Comment by chapmanjacobd** [comment]
> when downloading, we can also specify the alias and it would create it automatically

Would it make sense to use a separate database file per category of things that you want to search ? This could then be a single channel or a group of channels with some more flexibility

**Comment by NotJoeMartinez** [comment]
Partially implemented this "Allow for searching by channel name and Rowid #32" 
The aliases are defined by rowIDs or channel name.
